### ISSUE TITLE
Badly imported image

### ISSUE THREAD

**Issue by auseta** [DarrenBerg1/QRcode-Site#2]
The image is not displayed. **Possible error in src attribute path**

**Comment by DarrenBerg1** [comment]
Thank you!  I cannot seem to figure out how to link the image properly.. I have changed the file path several times, I am confused at how to fix it.

**Comment by DarrenBerg1** [comment]
It works outside of github, but when i launch the live page it does not work properly.

**Comment by auseta** [comment]
> It works outside of github, but when i launch the live page it does not work properly.

From what I see, the link provided to Frontendmentor already works!

**Comment by auseta** [comment]
The site on Live Server also loads the image correctly. U made it 😎

**Comment by DarrenBerg1** [comment]
Thanks again!!
